name: Auto-assign PR creator

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR creator as assignee
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const assignee = context.payload.pull_request.user.login;

            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: number,
              assignees: [assignee]
            });

            console.log(`Assigned ${assignee} to PR #${number}`);
